name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5  # To save the image locally
  path: ^1.9.1
  google_fonts: ^6.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  google_ml_kit: ^0.7.0
  flutter_svg: ^2.0.7  # For SVG support
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/norahvision_logo.svg
    
